server:
  port: 19094

spring:
  application:
    name: delivery-service
  profiles:
    default: dev
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: postgres
    password: postgres123!
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

#management:
#  zipkin:
#    tracing:
#      endpoint: "http://localhost:9411/api/v2/spans"
#  tracing:
#    sampling:
#      probability: 1.0