server:
  port: 19094

spring:
  application:
    name: delivery-service
  profiles:
    default: dev
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: postgres
    password: postgres123!
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

naver:
  map:
    geocoding-url: https://naveropenapi.apigw.ntruss.com/map-geocode/v2
    directions-url: https://naveropenapi.apigw.ntruss.com/map-direction/v1
    api-key-id: ${NAVER_API_KEY_ID}
    api-key: ${NAVER_API_KEY}

google:
  api:
    key: AIzaSyBM53zRSF5wxFe0DP86mqGkEO9382PUU0w
#management:
#  zipkin:
#    tracing:
#      endpoint: "http://localhost:9411/api/v2/spans"
#  tracing:
#    sampling:
#      probability: 1.0